---
# handlers/main.yml (mozjpeg)
# Prefix : mozjpeg

- name: "Print warning for mozjpeg (Check for deleted variables)"
  debug:
    msg: "{{ __mozjpeg_check_deleted_vars.stdout_lines }}"
  failed_when: yes
  ignore_errors: yes
